### PR TITLE
Add support for gpg keys with password

### PR DESCRIPTION
**Pull request by koenpunt**
A new (optional) option `gpg-private-key-passphrase` has been added, which can be used to specify the passphrase for the GPG key.

### CODE REVIEW

**Review by Kerren-Entrostat — COMMENTED** [review]
Thanks so much for contributing the library! This is awesome :)!

**Comment by Kerren-Entrostat** [comment]
@koenpunt 

I've merged this into dev, I'm just going to write some unit tests to ensure it's working correctly and then I'll take it live :smile: 

Thanks so much for the contribution, I'll get this built and live on the actions marketplace asap!

**Comment by Kerren-Entrostat** [comment]
@koenpunt I know I've already merged and I think this is cool for passphrases that don't have special characters or spaces but I think that spaces are killing it :/ I'm working on a branch here:

https://github.com/entrostat/git-secret-action/tree/fix/passphrase-failing

Any suggestions for what can be done? I have tried a couple but none seem to be working :disappointed:

**Comment by koenpunt** [comment]
I'm using it with a password with an asterisk in it, and that works. 
I'll have a look at passwords with spaces later this week.

**Comment by koenpunt** [comment]
But it might actually be enough to quote the variable passed to the reveal command;

git secret reveal "$pass_arg"

**Comment by Kerren-Entrostat** [comment]
@koenpunt I got it all sorted :+1: Just needed a bit of the `printf` goodness!

**Pull request merged**
